### ISSUE TITLE
ゆうき君の拠点　再び、７２，５５

### ISSUE THREAD

**Issue by Yumenoshima** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#101]

**Comment by takeshiman** [comment]
０４時～０７時５０分　ゆうき君起床　中断　ワニ3匹X門前門中枯らし

**Comment by takeshiman** [comment]
02時５０分　タマヌキ開始

![Image](https://user-images.githubusercontent.com/111450202/186736568-92e971b7-892d-4dea-a3a3-14767eb38820.png)

**Comment by takeshiman** [comment]
![Image](https://user-images.githubusercontent.com/111450202/189305182-72817a89-2d50-4c44-9c57-60713daabb83.png)

タマヌキ開始１７：１９
