### ISSUE TITLE
「chips」の拠点 (62, 80)

### ISSUE THREAD

**Issue by kimtechphone** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#102]
![Image](https://user-images.githubusercontent.com/111748158/186546325-47079eef-6759-43be-bb2c-c55def1051b6.png)

中にプラントXあり
拠点は鉄だけど恐竜門ゲートはただの木なのですぐ壊せる

**Comment by Yumenoshima** [comment]
![image](https://user-images.githubusercontent.com/17561997/186905659-d3ea6605-d385-4a93-8fc3-00797369d4e2.png)
