### ISSUE TITLE
草食島拠点

### ISSUE THREAD

**Issue by kimtechphone** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#130]
![Image](https://user-images.githubusercontent.com/111748158/188771432-3d693b45-e785-45a4-99a6-0e9549adb0b5.png)

**Comment by takeshiman** [comment]
![Image](https://user-images.githubusercontent.com/111450202/188773081-b539fb86-39c4-42f8-a4f8-0f08ff5cae0e.png)

**Comment by Yumenoshima** [comment]
![image](https://user-images.githubusercontent.com/17561997/188777546-0e872380-4ee6-4f31-9975-5455d71e6d05.png)
