### ISSUE TITLE
水中での石建造物爆破実験

### ISSUE THREAD

**Issue by Yumenoshima** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#40]
![Image](https://user-images.githubusercontent.com/84226674/185171395-de5a1e38-4860-48fc-9d1e-2ca63935b8f5.png)

**Comment by hirokunchan** [comment]
![Image](https://user-images.githubusercontent.com/84226674/185175496-35242432-6324-41d5-8675-0e05c3dc668d.png)

**Comment by hirokunchan** [comment]
爆破できます
![Image](https://user-images.githubusercontent.com/84226674/185176038-806241c0-2cb7-4a8a-a59c-9cb7026928fa.png)
