### ISSUE TITLE
「可口可乐」のレッドウッド拠点

### ISSUE THREAD

**Issue by Yumenoshima** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#46]
![Image](https://user-images.githubusercontent.com/17561997/185372133-108b2c27-e719-494d-bd5c-5b198d6433bb.png)

![Image](https://user-images.githubusercontent.com/17561997/185372233-6893b64c-4e57-41dc-be53-0d9dbf34aad6.png)

![Image](https://user-images.githubusercontent.com/17561997/185372334-15842658-2355-454e-a766-220940428180.png)

**Comment by takeshiman** [comment]
月曜日２３時プレイ確認

**Comment by takeshiman** [comment]
鳥乗ったやつがレッドウッド来たんで　中止　グレは　よっしー乳首にしまいました。
[07:14]
寝ます。

**Comment by takeshiman** [comment]
04時タマヌキ開始

**Comment by Yumenoshima** [comment]
![Image](https://user-images.githubusercontent.com/17561997/186271001-9fd98001-b896-4df4-a39d-c74a1b6a3301.png)

**Comment by Yumenoshima** [comment]
![Image](https://user-images.githubusercontent.com/17561997/186279560-b6e26d94-9b41-4975-86d0-d8305053d14b.png)

**Comment by takeshiman** [comment]
０７時５０分　テイらコレオ８５ｌｖ乗ったやつきたので中断
Ｌｖ８５ティらコレオ、プテラ、Ｌｖ４５ムカデ殺　門前、門中の一部Ｘ枯らし。

**Comment by kimtechphone** [comment]
https://www.battlemetrics.com/players/1100729853
[pfas7ybmx](https://www.battlemetrics.com/players/1107269568)
