### ISSUE TITLE
「良辰」の北部拠点

### ISSUE THREAD

**Issue by Yumenoshima** [Yumenoshima/ARK-Beginner-PvP-Official-Island-425-426-428#62]
![Image](https://user-images.githubusercontent.com/17561997/185405652-7dce5d07-f7f0-4927-8353-52cf1de247eb.png)

![Image](https://user-images.githubusercontent.com/17561997/185405202-904d31d8-9a38-4ff5-a8b1-b90892960732.png)

![Image](https://user-images.githubusercontent.com/17561997/185405032-bbc32447-fe29-4146-b8c6-c7ae2da5a4cd.png)

**Comment by Yumenoshima** [comment]
![image](https://user-images.githubusercontent.com/17561997/185464977-2fe0470c-567c-4f7e-86df-8ac894d64f91.png)

**Comment by takeshiman** [comment]
月曜日　２３時　プレイ確認

**Comment by Yumenoshima** [comment]
![image](https://user-images.githubusercontent.com/17561997/186416093-812e1d6d-9707-4a90-adb6-305a37fd8d25.png)

**Comment by Yumenoshima** [comment]
![Image](https://user-images.githubusercontent.com/17561997/188173944-cd6b7e9c-9474-4481-a838-5277d6c0e236.png)

**Comment by Yumenoshima** [comment]
![Image](https://user-images.githubusercontent.com/17561997/188174232-ab9eee0f-07c5-4f03-bdde-20494ac32c06.png)



![Image](https://user-images.githubusercontent.com/17561997/188174300-32cf3bd8-93ad-4c8f-9f2f-1c0917ca72ff.png)

**Comment by Yumenoshima** [comment]
![Image](https://user-images.githubusercontent.com/17561997/188192049-049d83ac-bf75-47c9-adbc-3c7389c8252d.png)
